language: php

dist: trusty
sudo: false

php:
#  - 5.6
  - 7.0
#  - 7.1
#  - 7.2
#  - nightly

git:
  depth: 1

services:
  - redis-server
  - mongodb

before_install:
  - sudo apt-get update
  - sudo apt-get install libpcre3-dev gcc make re2c
  - sudo git clone https://github.com/phalcon/cphalcon.git --depth=1
  - cd cphalcon/build
  - sudo ./install
  - phpenv config-add $TRAVIS_BUILD_DIR/tests/_ci/phalcon.ini
    # We use this file as our custom PHP config
  - phpenv config-add $TRAVIS_BUILD_DIR/tests/_ci/ci.ini
  - composer self-update
  - echo "extension = phalcon.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer install --prefer-dist --optimize-autoloader --quiet
  - cp .env.example .env
  - php run

before_script:
  - mysql -u root -e 'CREATE DATABASE phalcon;'
  - php run server:socket --daemonize

script:
  - ./vendor/bin/phpunit