language: php

dist: trusty
sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

git:
  depth: 1

services:
  - redis-server
  - mongodb

before_install:
  - composer self-update
  - pecl install phalcon
  - pecl install swoole
  - echo "extension = phalcon.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = swoole.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer install --prefer-dist --optimize-autoloader --quiet
  - cp .env.example .env
  - php run

before_script:
  - mysql -u root -e 'CREATE DATABASE phalcon;'
  - php run server:socket --daemonize

script:
  - ./vendor/bin/phpunit