<?php
// +----------------------------------------------------------------------
// | RelationTest.php [ WE CAN DO IT JUST THINK IT ]
// +----------------------------------------------------------------------
// | Copyright (c) 2016-2017 limingxinleo All rights reserved.
// +----------------------------------------------------------------------
// | Author: limx <715557344@qq.com> <https://github.com/limingxinleo>
// +----------------------------------------------------------------------
namespace Tests\Models;

use App\Common\Model\SqlCount;
use App\Models\Book;
use App\Models\User;
use Tests\UnitTestCase;

class RelationTest extends UnitTestCase
{
    protected function setUp()
    {
        SqlCount::getInstance()->flush();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testHasOne()
    {
        $user = User::findFirst(1);

        /** @var Book $book */
        foreach ($user->book as $book) {
            $books[] = $book->name;
        }

        $this->assertEquals(
            [
                'Hello World',
                '7天放弃PHP',
                '1周精通Go语言'
            ],
            $books
        );
    }
}
